# Generated by Django 4.1 on 2022-08-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_deck_alter_flashcard_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deck',
            new_name='Subject',
        ),
    ]