# Generated by Django 4.1 on 2022-08-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_flashcard_user_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='user_subject',
        ),
    ]